apiVersion: v1
kind: ConfigMap
metadata:
  name: boocol-app-configs
  namespace: default
  labels:
    app: boocol-app-configs
data:
  APP_ENV: "development"
  APP_DEBUG: "true"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "book_collection"